version: '3.7'

services:
  vr:
    container_name: vr
    image: vr:latest
    build: .
    environment:
      VR_NOTIFIERSETTINGS__DISCORDSETTINGS__APIKEY: "${VR_NOTIFIERSETTINGS__DISCORDSETTINGS__APIKEY}"
      VR_VRORCHESTRATORSERVICESETTINGS__SCRAPEINTERVALMINUTES: "${VR_VRORCHESTRATORSERVICESETTINGS__SCRAPEINTERVALMINUTES}"
      VR_CONNECTIONSTRINGS__DB: "${VR_CONNECTIONSTRINGS__DB}"
    networks:
      - vr
    restart: always
      
networks:
  vr:
    name: custom_vr