version: '3.7'

services:
  vr:
    container_name: vr
    image: vr:latest
    build: .
    environment:
      VR_NOTIFIERSETTINGS__DISCORDSETTINGS__APIKEY: "${VR_NOTIFIERSETTINGS__DISCORDSETTINGS__APIKEY}"
      VR_SCRAPESETTINGS__SCRAPEINTERVALMINUTES: "${VR_SCRAPESETTINGS__SCRAPEINTERVALMINUTES}"
      VR_SCRAPESETTINGS__CHROMEPATH: "${VR_SCRAPESETTINGS__CHROMEPATH}"
      VR_CONNECTIONSTRINGS__DB: "${VR_CONNECTIONSTRINGS__DB}"
    networks:
      - vr
    restart: always
      
networks:
  vr:
    name: custom_vr